import { spawnSync } from 'node:child_process'
import { existsSync, unlinkSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(new URL('.', import.meta.url)))
const SWIFT_SCRIPT = path.join(__dirname, 'bin', 'vision-ocr.swift')

/**
 * Handles error output from the Swift OCR module.
 * @param {string} stdout - Standard output string.
 * @param {string} stderr - Standard error string.
 * @param {number|null} status - Exit status code.
 * @throws {Error} - Throws detailed error.
 */
function handleOCRError(stdout, stderr, status) {
  try {
    const result = JSON.parse(stdout)
    throw new Error(result.error || 'OCR module exited with non-zero status')
  } catch {
    throw new Error(`OCR module failed with status ${status}: ${stderr}`)
  }
}

/**
 * Parses the raw output from the Swift OCR module.
 * @param {string} stdout - Standard output string.
 * @param {string} stderr - Standard error string.
 * @param {number|null} status - Exit status code.
 * @returns {object} - { text, imagePath }
 */
function parseOCROutput(stdout, stderr, status) {
  if (status !== 0) {
    handleOCRError(stdout, stderr, status)
  }

  try {
    const result = JSON.parse(stdout)
    if (result.error) throw new Error(result.error)
    return {
      text: result.text || '',
      imagePath: result.imagePath || undefined,
    }
  } catch (error) {
    throw new Error('Failed to parse OCR result', { cause: error })
  }
}

/**
 * Executes the native Swift OCR module.
 * Cross-referenced with PRD FR-03 and ARCHITECTURE Section 2.
 * @param {string} filePath - Absolute path to document.
 * @returns {Promise<object>} - OCR results object.
 */
export async function runOCR(filePath) {
  if (!existsSync(filePath)) {
    throw new Error(`File not found: ${filePath}`)
  }

  // Use absolute path for swift to satisfy sonarjs/no-os-command-from-path
  const swiftPath = '/usr/bin/swift'
  const actualPath = existsSync(swiftPath) ? swiftPath : 'swift'

  const process = spawnSync(actualPath, [SWIFT_SCRIPT, filePath], {
    encoding: 'utf8',
    maxBuffer: 10 * 1024 * 1024,
  })

  if (process.error) {
    throw new Error(`Failed to execute OCR module: ${process.error.message}`, {
      cause: process.error,
    })
  }

  return parseOCROutput(process.stdout, process.stderr, process.status)
}

/**
 * Cleans up temporary image files generated by the OCR module.
 * @param {string|undefined} imagePath - Path to temp image.
 */
export function cleanupOCRImage(imagePath) {
  if (!imagePath) return

  if (imagePath.includes('/T/')) {
    try {
      if (existsSync(imagePath)) {
        unlinkSync(imagePath)
      }
    } catch {
      // Silent fail
    }
  }
}
