import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { existsSync, unlinkSync } from 'node:fs';

const __dirname = path.dirname(fileURLToPath(new URL('.', import.meta.url)));
const SWIFT_SCRIPT = path.join(__dirname, 'bin', 'vision-ocr.swift');

/**
 * Parses the raw output from the Swift OCR module.
 * @param {string} stdout
 * @param {string} stderr
 * @param {number|null} status
 * @returns {object}
 */
function parseOCROutput(stdout, stderr, status) {
  if (status !== 0) {
    try {
      const result = JSON.parse(stdout);
      throw new Error(result.error || 'OCR module exited with non-zero status');
    } catch {
      throw new Error(`OCR module failed with status ${status}: ${stderr}`);
    }
  }

  try {
    const result = JSON.parse(stdout);
    if (result.error) throw new Error(result.error);
    return {
      text: result.text || '',
      imagePath: result.imagePath || undefined,
    };
  } catch (error) {
    throw new Error('Failed to parse OCR result', { cause: error });
  }
}

/**
 * Executes the native Swift OCR module.
 * Cross-referenced with PRD FR-03 and ARCHITECTURE Section 2.
 * @param {string} filePath - Absolute path to document.
 * @returns {Promise<object>} - { text, imagePath }
 */
export async function runOCR(filePath) {
  if (!existsSync(filePath)) {
    throw new Error(`File not found: ${filePath}`);
  }

  const process = spawnSync('swift', [SWIFT_SCRIPT, filePath], {
    encoding: 'utf8',
    maxBuffer: 10 * 1024 * 1024,
  });

  if (process.error) {
    throw new Error(`Failed to execute OCR module: ${process.error.message}`, { cause: process.error });
  }

  return parseOCROutput(process.stdout, process.stderr, process.status);
}

/**
 * Cleans up temporary image files generated by the OCR module.
 * @param {string|undefined} imagePath - Path to temp image.
 */
export function cleanupOCRImage(imagePath) {
  if (!imagePath || !existsSync(imagePath)) return;

  // Only unlink if it's in a temporary directory to be safe
  if (imagePath.includes('/T/')) {
    try {
      unlinkSync(imagePath);
    } catch {
      // Silent fail
    }
  }
}
